sudo: required
language: java
jdk: oraclejdk8
install: true
env:
  global:
    - secure: "the base64 string from when you encrypted SONATYPE_USERNAME"
    - secure: "the base64 string from when you encrypted SONATYPE_PASSWORD"
    - secure: "the base64 string from when you encrypted GPG_KEY_NAME"
    - secure: "the base64 string from when you encrypted GPG_PASSPHRASE"
  local:
    maven: repository=$HOME/.m2

services:
- docker

addons:
  sonarqube:
    organization: processpuzzle
    token:
      secure: "$SONAR_TOKEN"
    branches:
    - development
    - master

before_install:
- openssl aes-256-cbc -K $encrypted_a8a500ff1127_key -iv $encrypted_a8a500ff1127_iv -in codesigning.asc.enc -out codesigning.asc -d
- gpg --fast-import codesigning.asc

cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.sonar/cache"

before_script: echo $AWS_ACCESS_KEY_ID

script:
  - mvn clean install org.jacoco:jacoco-maven-plugin:prepare-agent sonar:sonar
  
before_deploy:

deploy:
  - provider: script
    skip_cleanup: true
    script: mvn deploy -Pdocker-build-deploy -Dmaven.test.skip=true -DskipIntegrationTests --settings travis-maven-settings.xml -Dsettings.security=travis-maven-settings-security.xml -B
    on:
      branch: master
      
  - provider: script
    skip_cleanup: true
    script: mvn deploy -Pdocker-build-deploy -Prelease-sign-artifacts -Dmaven.test.skip=true -DskipIntegrationTests --settings travis-maven-settings.xml -Dsettings.security=travis-maven-settings-security.xml -B
    on:
      branch: master
      tags: true
  
notifications:
  email: false
