sudo: required

language: java
jdk: oraclejdk8
install: true

env:
  global:
    - secure: "the base64 string from when you encrypted SONATYPE_USERNAME"
    - # ^^ SONATYPE_USERNAME
    - secure: "the base64 string from when you encrypted SONATYPE_PASSWORD"
    - # ^^ SONATYPE_PASSWORD
    - secure: "the base64 string from when you encrypted GPG_KEY_NAME"
    - # ^^ GPG_KEY_NAME
    - secure: "the base64 string from when you encrypted GPG_PASSPHRASE"
    - # ^^ GPG_PASSPHRASE
  local:
    maven:
      repository=$HOME/.m2

services:
  - docker

addons:
  sonarqube:
    organization: "processpuzzle"
    token:
      secure: $SONAR_TOKEN
    branches :
    - development
    - master

before_install:

cache:
  directories:
  - $HOME/.m2
  - $HOME/.sonar/cache

before_script: echo $AWS_ACCESS_KEY_ID

script:
  - mvn clean install org.jacoco:jacoco-maven-plugin:prepare-agent sonar:sonar
  
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - openssl aes-256-cbc -K $encrypted_8a18e2dcf8ad_key -iv $encrypted_8a18e2dcf8ad_iv -in codesigning.asc.enc -out codesigning.asc -d
  - chmod +x cd/before-deploy.sh 
  - ./cd/before-deploy.sh
  
before_deploy:

deploy:
  - provider: script
    skip_cleanup: true
    script: mvn deploy -Pdocker-build-deploy -Dmaven.test.skip=true -DskipIntegrationTests --settings travis-maven-settings.xml -Dsettings.security=travis-maven-settings-security.xml -B
    on:
      branch: master
      
  - provider: script
    skip_cleanup: true
    script: mvn deploy -Pdocker-build-deploy -Prelease-sign-artifacts -Dmaven.test.skip=true -DskipIntegrationTests --settings travis-maven-settings.xml -Dsettings.security=travis-maven-settings-security.xml -B
    on:
      branch: master
      tags: true

notifications:
  email: false