sudo: required

language: java
jdk: oraclejdk8

services:
  - docker

addons:
  sonarqube:
    organization: "processpuzzle"

cache:
  directories:
  - $HOME/.m2
  - $HOME/.sonar/cache

script:
  # other script steps might be done before running the actual SonarQube analysis
  - sonar-scanner

deploy:
  - provider: script
    skip_cleanup: true
    script: mvn deploy -Pdocker-build-deploy, deploy-to-aws --settings travis-maven-settings.xml -DskipTests=true -B
    on:
      branch: development
  - provider: script
    skip_cleanup: true
    script: mvn deploy -Pdocker-build-deploy, deploy-to-aws --settings travis-maven-settings.xml -DskipTests=true -B
    on:
      branch: master
  
after_success:
  - bash <(curl -s https://codecov.io/bash)
