sudo: required

language: java
jdk: oraclejdk8

env:
- local.maven.repository=$HOME/.m2

services:
  - docker

addons:
  sonarqube:
    organization: "processpuzzle"

cache:
  directories:
  - $HOME/.m2
  - $HOME/.sonar/cache

script:
  # other script steps might be done before running the actual SonarQube analysis
  - sonar-scanner

deploy:
  - provider: script
    skip_cleanup: true
    script: mvn deploy -Pdocker-build-deploy -Passembly-aws-bundle -DskipTests=true --settings travis-maven-settings.xml -Dsettings.security=travis-maven-settings-security.xml -B
    on:
      branch: development
  - provider: script
    skip_cleanup: true
    script: mvn deploy -Pdocker-build-deploy -Passembly-aws-bundle -DskipTests=true --settings travis-maven-settings.xml -Dsettings.security=travis-maven-settings-security.xml -B
    on:
      branch: master
  
after_success:
  - bash <(curl -s https://codecov.io/bash)
