sudo: required

language: java
jdk: oraclejdk8

services:
  - docker

install: true
cache:
  directories:
  - $HOME/.m2

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - mvn deploy --settings travis-maven-settings.xml -DskipTests=true -B

deploy:
  skip_cleanup: true
  provider: script
  script: mvn deploy --settings travis-maven-settings.xml -DskipTests=true -B -Pdocker-deploy
  on:
    branch: development