DROP TABLE account if EXISTS ;
DROP TABLE CLIENT_DETAILS if EXISTS ;

create table ACCOUNT ( ACCOUNT_NAME varchar(255) not null,
                      PASSWORD varchar(255 ) not null,
                      ID bigint GENERATED BY DEFAULT AS IDENTITY(START WITH 100, INCREMENT BY 1) PRIMARY KEY,
                      ENABLED boolean default true)  ;

create table client_details(
  CLIENT_ID VARCHAR (255) not null unique ,
  CLIENT_SECRET VARCHAR (255) not null   ,
  RESOURCE_IDS VARCHAR (255) null ,
  SCOPES VARCHAR (255) null ,
  GRANT_TYPES VARCHAR (255) null ,
  AUTHORITIES VARCHAR (255) null
);