logging:
  level:
    root: INFO
    org.springframework: INFO
    org.springframework.beans: INFO
    org.springframework.security: INFO
    com.processpuzzle.fitnesse.connect: DEBUG

spring:
  datasource:
    url: jdbc:h2:mem:test_mem;DB_CLOSE_ON_EXIT=FALSE
    username: SA
    
wiremock:
  port: 8089
