logging:
  level:
    root: WARN
    org.springframework: INFO
    org.springframework.beans: INFO
    org.springframework.security: INFO

spring:
  datasource:
    url: jdbc:h2:mem:test_mem;DB_CLOSE_ON_EXIT=FALSE
    username: SA
    
wiremock:
  port: 8089
