logging:
  level:
    org.springframework: INFO

connector:
  contextRoot: 
  host: localhost
  port: 9124
  dataSourceConfiguration:
    username: SA
    password: 
    testWhileIdle: true
    driverClassName: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/connector-test
    validationQuery: SELECT 1
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: 
    show-sql: true
    