server:
  port: 9124
  contextPath: /

security:
  headers:
    cache: false

endpoints:
  shutdown:
    sensitive: false
    enabled: true

storage:
  location: target/upload-dir

spring:
  http:
    multipart:
      max-file-size: 128KB
      max-request-size: 128KB
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
